# Generated by Django 3.2.12 on 2022-05-04 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('custom_order', models.BooleanField(default=False)),
                ('pd_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pd_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_sph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_cyl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_axis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('right_add', models.CharField(default='None', max_length=100, null=True)),
                ('left_sph', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_cyl', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_axis', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('left_add', models.CharField(default='None', max_length=100, null=True)),
                ('prism', models.BooleanField(default=False)),
                ('lens_type', models.CharField(default='None', max_length=25, null=True)),
                ('rx_type', models.CharField(default='None', max_length=25, null=True)),
                ('lens_coat', models.CharField(default='None', max_length=25, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
