# Generated by Django 3.2.12 on 2022-04-24 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, upload_to=products.models.category_image_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(default='Ludwin Dieter', max_length=100)),
                ('manufacturer', models.CharField(default='Ludwin Dieter', max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('oxygen', models.CharField(default='87', max_length=10, null=True)),
                ('water', models.CharField(default='147 Dk/T', max_length=10, null=True)),
                ('frequency', models.CharField(default='weekly', max_length=30, null=True)),
                ('usage_desc', models.CharField(default='7 days usage', max_length=100, null=True)),
                ('usage', models.CharField(default='Weekly', max_length=1000, null=True)),
                ('gender', models.CharField(default='Uni-sex', max_length=10, null=True)),
                ('year', models.IntegerField(blank=True, default='2020', null=True)),
                ('upc', models.CharField(default='', max_length=20, null=True)),
                ('tags', models.TextField(blank=True, default='Random', null=True)),
                ('shape', models.CharField(default='square', max_length=30, null=True)),
                ('style', models.CharField(default='Full Rim', max_length=20, null=True)),
                ('uv', models.CharField(default='', max_length=20, null=True)),
                ('progressive', models.BooleanField(default=False)),
                ('customizable', models.BooleanField(default=False)),
                ('frame_material', models.CharField(default='Acetate', max_length=20, null=True)),
                ('lens_material', models.CharField(default='CR39', max_length=20, null=True)),
                ('pd_range', models.CharField(default='61-85mm', max_length=20, null=True)),
                ('presc_range', models.CharField(default='-7.00 ~ +7.00', max_length=20, null=True)),
                ('age_range', models.CharField(default='', max_length=20, null=True)),
                ('size', models.IntegerField(default=0)),
                ('lens_color', models.TextField(blank=True, default='Black', null=True)),
                ('color', models.TextField(blank=True, default='Black', null=True)),
                ('marked_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('image1', models.ImageField(blank=True, upload_to=products.models.product_image_path)),
                ('image2', models.ImageField(blank=True, upload_to=products.models.product_image_path)),
                ('image3', models.ImageField(blank=True, upload_to=products.models.product_image_path)),
                ('image4', models.ImageField(blank=True, upload_to=products.models.product_image_path)),
                ('image5', models.ImageField(blank=True, upload_to=products.models.product_image_path)),
                ('details', models.TextField(blank=True, null=True)),
                ('accessories', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('views', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='products.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=250)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
