# Generated by Django 3.2.12 on 2022-04-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220313_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.TextField(default='black'),
        ),
        migrations.AddField(
            model_name='product',
            name='frame_material',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='uni-sex', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='lens_material',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='progressive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='range',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, default='Fashion', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uv',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Classic Glasses', max_length=250),
        ),
    ]
