# Generated by Django 3.2.12 on 2022-04-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220419_2254'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='Images',
        ),
    ]
