# Generated by Django 3.2.12 on 2022-04-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_picture_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='file',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='product',
        ),
    ]
