# Generated by Django 3.2.12 on 2022-04-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20220421_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type_tag',
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, default='Random', null=True),
        ),
    ]
