# Generated by Django 3.2.12 on 2022-04-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20220421_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lens_color',
            field=models.TextField(blank=True, default='Black', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_desc',
            field=models.CharField(default='7 days usage', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.TextField(blank=True, default='Black', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='frame_material',
            field=models.CharField(default='Acetate', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='frequency',
            field=models.CharField(default='weekly', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(default='Uni-sex', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lens_material',
            field=models.CharField(default='CR39', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='Ludwin Dieter', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='oxygen',
            field=models.CharField(default='87', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pd_range',
            field=models.CharField(default='61-85mm', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='presc_range',
            field=models.CharField(default='-7.00 ~ +7.00', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shape',
            field=models.CharField(default='square', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(default='Full Rim', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage',
            field=models.CharField(default='Weekly', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='water',
            field=models.CharField(default='147 Dk/T', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.IntegerField(blank=True, default='2020', null=True),
        ),
    ]
